# Generated by Django 2.2.3 on 2019-10-23 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mix_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=255)),
                ('mix_status', models.CharField(default='awaiting deposit ...', max_length=255)),
                ('deposit_address', models.CharField(default='', max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=0)),
                ('message', models.CharField(default='', max_length=500)),
                ('txid', models.CharField(default='not yet', max_length=500)),
                ('confirmations', models.IntegerField(default=1)),
                ('current_confirmations', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('address', models.CharField(max_length=1000)),
                ('delay', models.IntegerField()),
                ('status', models.CharField(default='not done', max_length=300)),
                ('amount_sent', models.FloatField(default=0)),
                ('message', models.CharField(default='', max_length=500)),
                ('txid', models.CharField(default='not sent yet', max_length=500)),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixer.Mix')),
            ],
        ),
    ]
