# Generated by Django 2.2.3 on 2019-10-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='deposit_amount',
            field=models.FloatField(default=0),
        ),
    ]
