# Generated by Django 2.2.3 on 2019-11-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0002_mix_deposit_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewProtection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
