# Generated by Django 2.2.3 on 2019-11-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0003_viewprotection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='mix',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mix',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
