# Generated by Django 2.2.3 on 2019-11-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0006_mix_validated_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='bonus',
            field=models.FloatField(default=0),
        ),
    ]
