# Generated by Django 2.2.3 on 2020-04-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixer', '0008_auto_20191212_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='mix',
            name='non_confirmed',
            field=models.FloatField(default=0),
        ),
    ]
