# Generated by Django 2.2.3 on 2019-10-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('small_description', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='assets/media/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('clicked', models.IntegerField(default=0)),
                ('tag', models.CharField(default='', max_length=255)),
                ('meta_title', models.CharField(default='', max_length=255)),
                ('meta_key', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_desc', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
            ],
        ),
    ]
