# Generated by Django 2.2.3 on 2019-10-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mix_id', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_fee', models.FloatField(default=0)),
                ('t_fee', models.FloatField(default=0)),
                ('support_mail', models.CharField(default='', max_length=300)),
                ('min_usr_pay', models.FloatField(default=0)),
                ('max_usr_pay', models.FloatField(default=0)),
                ('max_usr_disp_pay', models.FloatField(default=0)),
                ('d_inactive', models.FloatField(default=0)),
                ('d_deleted', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
