# Generated by Django 2.2.3 on 2019-11-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='donation',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='settings',
            name='protection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='shuffle_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='shuffle_perc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='site',
            field=models.CharField(default='', max_length=300),
        ),
    ]
