# Generated by Django 2.2.3 on 2019-12-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0002_auto_20191104_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='banner_color',
            field=models.CharField(default='red', max_length=255),
        ),
        migrations.AddField(
            model_name='settings',
            name='banner_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='banner_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='settings',
            name='bold',
            field=models.BooleanField(default=False),
        ),
    ]
