# Generated by Django 2.2.3 on 2019-12-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0003_auto_20191220_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='bold',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
