# Generated by Django 2.2.3 on 2020-02-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0004_auto_20191220_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='mirror',
            field=models.TextField(default=''),
        ),
    ]
