# Generated by Django 2.2.3 on 2020-05-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0005_settings_mirror'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=300)),
                ('keywords', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=500)),
                ('cronical', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
